import type { Metadata } from "next";
import { CssVarsProvider } from "@mui/joy/styles";
import "@fontsource/inter";

export const metadata: Metadata = {
	title: "Google Maps Platform Hackathon",
	description: "Generated by Mami",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body>
				<CssVarsProvider>{children}</CssVarsProvider>
			</body>
		</html>
	);
}
